laravel/routes/web.php
<?php

use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('admin.dashboard.index');
})->name('dashboard');

Route::get('/c/home', function () {
    return view('client.layouts.app');
});

Route::resource('roles', RoleController::class);
//Route::resource('users', UserController::class);


Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

laravel/app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Spatie\Permission\Models\Role as ModelRole;

class Role extends ModelRole
{
    use HasFactory;

    protected $fillable = [
        'name',
        'display_name',
        'group',
        'guard_name'
    ];

    protected function guardName(): Attribute
    {
        return Attribute::make(
            set: fn ($value) => 'web',
        );
    }
}

laravel/app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Role\CreateRoleRequest;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::latest('id')->paginate(3);

        return view('admin.roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::all()->groupBy('group');

        return view('admin.roles.create', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRoleRequest $request)
    {
        $dataCreate = $request->all();

        $role = Role::create($dataCreate);
        $role->permissions()->attach($dataCreate['permission_ids']);

        return to_route('roles.index')->with(["message" => "Create success"]);
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::with('permissions')->findOrFail($id);
        $permissions = Permission::all()->groupBy('group');

        return view('admin.roles.edit', compact('role', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $role = Role::findOrFail($id);
        $dataUpdate = $request->all();
        $role->update($dataUpdate);
        $role->permissions()->sync($dataUpdate['permission_ids']);

        return to_route('roles.index')->with(["message" => "Update success"]);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

laravel/resources/views/admin/roles/create.blade.php
@extends('admin.layouts.app')

@section('title', 'Create role')

@section('content')
    <div class="card">
        <h1>Create role</h1>

        <form action="{{route("roles.store")}}" method="post">
            @csrf
            <div class="input-group input-group-static mb-4">
                <label>Name</label>
                <input type="text" value="{{ old('name') }}" class="form-control" name="name">
                @error('name')
                    <span class="text-danger">{{ $message }}</span>
                @enderror
            </div>
            <div class="input-group input-group-static mb-4">
                <label>Display name</label>
                <input type="text" value="{{ old('display_name') }}" class="form-control" name="display_name">
                @error('display_name')
                <span class="text-danger">{{ $message }}</span>
                @enderror
            </div>
            <div class="input-group input-group-static mb-4">
                <label for="exampleFormControlSelect1" class="ms-0" >Group</label>
                <select class="form-control" id="exampleFormControlSelect1" name="group">
                    <option value="system">System</option>
                    <option value="user">User</option>
                </select>
                @error('group')
                <span class="text-danger">{{ $message }}</span>
                @enderror
            </div>
            <div class="input-group input-group-outline is-invalid my-3">
                @foreach($permissions as $groupName => $permission)
                    <div class="col-6">
                        <h4>{{ $groupName }}</h4>
                        <div>
                            @foreach($permission as $item)
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="permission_ids[]"
                                           value="{{$item->id}}">
                                    <label class="custom-control-label"
                                           for="customCheck1">{{ $item->display_name }}</label>
                                </div>
                            @endforeach
                        </div>
                    </div>
                @endforeach
            </div>
            <button type="submit" class="btn btn-submit btn-primary">Submit</button>
        </form>
    </div>
@endsection

laravel/resources/views/admin/roles/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'Create role' . $role->name)

@section('content')
    <div class="card">
        <h1>Edit role</h1>

        <form action="{{route("roles.update", $role->id)}}" method="POST">
            @csrf
            @method('PUT')
            <div class="input-group input-group-static mb-4">
                <label>Name</label>
                <input type="text" value="{{ old('name') ?? $role->name}}" class="form-control" name="name">
                @error('name')
                <span class="text-danger">{{ $message }}</span>
                @enderror
            </div>
            <div class="input-group input-group-static mb-4">
                <label>Display name</label>
                <input type="text" value="{{ old('display_name') ?? $role->display_name }}" class="form-control"
                       name="display_name">
                @error('display_name')
                <span class="text-danger">{{ $message }}</span>
                @enderror
            </div>
            <div class="input-group input-group-static mb-4">
                <label for="exampleFormControlSelect1" class="ms-0">Group</label>
                <select class="form-control" id="exampleFormControlSelect1" name="group" value="{{ $role->group }}">
                    <option value="system">System</option>
                    <option value="user">User</option>
                </select>
                @error('group')
                <span class="text-danger">{{ $message }}</span>
                @enderror
            </div>
            <div class="input-group input-group-outline is-invalid my-3">
                @foreach($permissions as $groupName => $permission)
                    <div class="col-6">
                        <h4>{{ $groupName }}</h4>
                        <div>
                            @foreach($permission as $item)
                                <div class="form-check">
                                    <input class="form-check-input"
                                           type="checkbox"
                                           {{ $role->permissions->contains('name', $item->name) ? 'checked' : ''}}
                                           name="permission_ids[]"
                                           value="{{$item->id}}">
                                    <label class="custom-control-label"
                                           for="customCheck1">{{ $item->display_name }}</label>
                                </div>
                            @endforeach
                        </div>
                    </div>
                @endforeach
            </div>
            <button type="submit" class="btn btn-submit btn-primary">Submit</button>
        </form>
    </div>
@endsection

laravel/resources/views/admin/roles/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Roles')

@section('content')
    @if(session('message'))
        <span>{{ session('message') }}</span>
    @endif

    <div class="card justify-content-center">
        Role list
    </div>
    <div>
        <a href="{{route('roles.create')}}" class="btn btn-primary">Create role</a>
    </div>
    <div>
        <table class="table table-hover">
            <tr>
                <td>#</td>
                <td>Name</td>
                <td>Display name</td>
                <td>Action</td>
            </tr>
            @foreach($roles as $role)
                <tr>
                    <td>{{ $role->id }}</td>
                    <td>{{ $role->name }}</td>
                    <td>{{ $role->display_name }}</td>
                    <td>
                        <a href="{{ route('roles.edit', $role->id) }}" class="btn btn-warning">Edit</a>
                        <a href="{{ route('roles.destroy', $role->id) }}" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            @endforeach
        </table>
        {{ $roles->links('pagination::bootstrap-4') }}
    </div>
@endsection